
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 2;
  public static final int DECIMAL = 4;
  public static final int ENTERO = 3;
  public static final int EOF = 0;
  public static final int PAR2 = 8;
  public static final int PAR1 = 7;
  public static final int FINCADENA = 5;
  public static final int error = 1;
  public static final int IMPRIMIR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "FINCADENA",
  "IMPRIMIR",
  "PAR1",
  "PAR2"
  };
}

